Mindgamesnl/OpenAudioMc

README.md
WebInterface/config.php
WebInterface/index.php
WebInterface/php/inc/index.php

Fixes and Improvements of the code.

Fixes and Improvements.

---

WebInterface/css/ui2.css

Makes the page mobile friendly <3

Mobile Friendly

---

WebInterface/php/inc/openaudio.php

removed those gaps and added comments to find each piece of code easier ;)

Fixes and Typos

---

WebInterface/css/ui2.css

This makes the alert now popup and is in fixed position to keep it from breaking again, plus adjusted the .middlePage class to be centered after it showing up at the bottom.

Fixes that werent posted before release

---

WebInterface/php/inc/openaudio.php

It will be more understanding when you look at css/ui2.css

Notification moved to bottom

---

Web client/files/pages/api_server_offline.php

Removed old bootstrap error class (Maybe merge?)

Removed old bootstrap style

---

Web client/index.html

Added comment in footer for developers

---

Plugin source code/src/net/openaudiomc/minecraft/Main.java

No need for cm_callback.update, since its already called in timeoutManager.updateCounter.

removed cm_callback.update();

---

.travis.yml

Travis fix for 3.0

---

LICENSE

Project stared in 2016 and it's now 2018 (I assume :thinking:)

Correct license year

---

.travis.yml
jitpack.yml

For Easier Plugin & Addon Development using the Maven Dependency System to automatically include Updates from OpenAudioMC

Created Jitpack Configuration and Fixed Travis CI

---

client/src/index.html

Not important PR, but just to throw it out there

Update Copyright Year

---

docs/traincarts.md

Changed from "You can add a piece of music to one of your trains through a sing and that's it." to "You can add a piece of music to one of your trains through a sign and that's it."

Spelling Error

---

plugin/src/main/resources/plugin.yml

Added command descriptions into the plugin.yml so that the /help and /? command show the description instead of null

Added command descriptions into the plugin.yml

---

client/src/nl.lang

The dutch translation for the client site

Translation OAMC in Dutch

---

plugin/src/main/java/com/craftmend/openaudiomc/generic/networking/client/objects/player/ClientConnection.java

Fix color showing up as YELLOW in chat.

Fix color showing up as YELLOW in chat.

---

plugin/src/main/java/com/craftmend/openaudiomc/generic/storage/enums/StorageKey.java
plugin/src/main/java/com/craftmend/openaudiomc/spigot/modules/players/listeners/PlayerConnectionListener.java
plugin/src/main/resources/config.yml

Just found this really annoying since I already use the mechanic for something else.

Make microphone toggle while sneaking and swapping optional in the config.

---

plugin/pom.xml
plugin/src/main/java/com/craftmend/openaudiomc/spigot/OpenAudioMcSpigot.java
plugin/src/main/java/com/craftmend/openaudiomc/spigot/modules/punishments/EssentialsIntegration.java
plugin/src/main/resources/plugin.yml

Add essentials because not everyone uses litebans

Add essentials integration for syncing mutes with voicechat

---

docs/production-client/target/fr.lang

Added french translation, i'll double check if i'v made any mistake

add french

---

docs/production-client/target/fr.lang

added new update translation
removed duplicate entry

Updated french

---

client/src/de.lang

And another one. Sorry 😅 
I don't know why I didn't notice that. 😅 
Greetings,
Ceddix

fixed line break errors

---

client/src/de.lang

Hi 👋🏻 
The German translations are now in line with the latest changes.
Greetings 😄

added and updated sentences

---

client/src/css/winter.css
client/src/index.html
docs/production-client/target/css/winter.css
docs/production-client/target/index.html

- weird size fix of "activate vc"
- align items voice chat
- align items voice chat settings
- improved support for all screensizes
- improved lay-out of general settings

Lay-out fix web client

---

client/src/de.lang

Hey! I noticed that some changes have been made, and therefore I have adapted and supplemented the German language file again.
I also wanted to mention, that the copyright in the top right corner of the audio server has not yet been adjusted:

updated german language

---

client/public/kr.lang

Please delete the "lang-kr.lang.txt" file in the directory. Thank you :)

language translation - Korean (fixed)

---

client/public/sv.lang
client/src/client/translations/MessageModule.jsx

Accidentally made two commits, but both added the swedish language. :)

Added the swedish language

---

client/public/zh-CN.lang
client/public/zh-TW.lang
client/src/client/translations/MessageModule.jsx

Added Traditional Chinese language and corrected some Simplified Chinese errors

Added Traditional Chinese and corrected some Simplified Chinese errors

---

client/public/de.lang

Hii 👋🏼 
Here are some updated translations for you 😄

updated German translation and added new locales

---

plugin/src/main/java/com/craftmend/openaudiomc/generic/networking/handlers/ClientChangedVolumeHandler.java
plugin/src/main/java/com/craftmend/openaudiomc/generic/networking/handlers/ClientInitializedRtcHandler.java
plugin/src/main/java/com/craftmend/openaudiomc/generic/node/packets/ClientUpdateStatePacket.java
plugin/src/main/java/com/craftmend/openaudiomc/generic/proxy/ProxyHostService.java
plugin/src/main/java/com/craftmend/openaudiomc/spigot/modules/proxy/listeners/BukkitPacketListener.java

Makes the volume value accurate in sub-servers by updating the client state properly.

WIP: Update the clientstate from the proxy on volume change

---

api/src/main/java/com/craftmend/openaudiomc/api/MediaApi.java
plugin/src/main/java/com/craftmend/openaudiomc/generic/api/implementaions/MediaApiImpl.java

Add API methods for preloading media/sources for specific clients. Has the same functionality as the preload command

Add API for preloading

---

client/src/oa.css
client/src/views/client/pages/voice/voicepage.css

The background images in the audio / voicechat Tab did not cover, they did repeat.

Cover backgrounds

---

plugin/src/main/java/com/craftmend/openaudiomc/generic/commands/interfaces/SubCommand.java
plugin/src/main/java/com/craftmend/openaudiomc/generic/commands/subcommands/HelpSubCommand.java

On `/voice help` the clickable cmds where mapped to `/oa help <subcmd>`

Fix help subcommand clickable messages

---

api/src/main/java/com/craftmend/openaudiomc/api/VoiceApi.java
api/src/main/java/com/craftmend/openaudiomc/api/voice/DisplayOverride.java
api/src/main/java/com/craftmend/openaudiomc/api/voice/VoicePeerOptions.java
client/public/metadata.json
client/src/client/services/media/MediaManager.jsx
client/src/client/services/media/objects/Channel.jsx
client/src/client/services/voice/peers/VoicePeer.jsx
client/src/client/services/voice/peers/VoicePeerOptions.jsx
client/src/components/voice/VoicePeerBox.jsx
client/src/components/voice/VoicePeerRow.jsx
client/src/metadata.json
plugin/src/main/java/com/craftmend/openaudiomc/generic/api/implementaions/VoiceApiImpl.java

Based on a recent feature request by a patreon.

Plugin-side API for custom voicechat display UUID's or names

---

client/public/pt-BR.lang
client/src/client/translations/MessageModule.jsx

Adds brazilian portuguese translation.

Add pt-br translation

---

api/src/main/java/com/craftmend/openaudiomc/api/clients/Client.java
api/src/main/java/com/craftmend/openaudiomc/api/clients/ClientBaseAuthentication.java
client/public/metadata.json
client/src/client/services/world/objects/Player.jsx
client/src/metadata.json
plugin/src/main/java/com/craftmend/openaudiomc/generic/client/objects/ClientConnection.java
plugin/src/main/java/com/craftmend/openaudiomc/generic/client/session/ClientAuth.java

Add simple authentication state-getters.
Just basic fundamentals for now, may be expanded in the future if needed.

Feat: auth api
